# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: gohide.gohide
PackageVersion: 5.8.2
InstallerLocale: en-US
MinimumOSVersion: 10.0.19041.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/gohide/GoHide/releases/download/v5.8.2/gohide-5.8.2-win-Setup.exe
  InstallerSha256: DB19D88AAF7CA02C4740C5BAD23727C50E1657A37CCE4AC7639ECD3A5C3EB706
  AppsAndFeaturesEntries:
  - DisplayName: gohide
    Publisher: Xianwei Zhu
    DisplayVersion: 5.8.2
    ProductCode: gohide
    InstallerType: exe
ManifestType: installer
ManifestVersion: 1.6.0
