# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: gohide.gohide
PackageVersion: 5.7.3
InstallerLocale: en-US
MinimumOSVersion: 10.0.19041.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/gohide/GoHide/releases/download/v5.7.3/gohide-5.7.3-win-Setup.exe
  InstallerSha256: 64B2F910703902371E1CFE5684DB5A2D32CCE21FC6D53E2B2E3CEC9AE9D7DA4B
  AppsAndFeaturesEntries:
  - DisplayName: gohide
    Publisher: Xianwei Zhu
    DisplayVersion: 5.7.3
    ProductCode: gohide
    InstallerType: exe
ManifestType: installer
ManifestVersion: 1.6.0
