# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: gohide.gohide
PackageVersion: 5.8.0
InstallerLocale: en-US
MinimumOSVersion: 10.0.19041.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
ReleaseDate: 2026-10-06
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/gohide/GoHide/releases/download/v5.8.0/gohide-5.8.0-win-Setup.exe
  InstallerSha256: 001FD26294E8BE7668924903464B9D64AA6F62E073E76186AF3B9279B2E0B5CF
  AppsAndFeaturesEntries:
  - DisplayName: gohide
    Publisher: Xianwei Zhu
    DisplayVersion: 5.8.0
    ProductCode: gohide
    InstallerType: exe
ManifestType: installer
ManifestVersion: 1.6.0
