# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: gohide.gohide
PackageVersion: 5.8.5
InstallerLocale: en-US
MinimumOSVersion: 10.0.19041.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
ReleaseDate: 2026-10-09
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/gohide/GoHide/releases/download/v5.8.5/gohide-5.8.5-win-Setup.exe
  InstallerSha256: F9EF9E4236D5ED07D4A4953FB7E6A71435B1FD14757D7D89502725A695F45B24
  AppsAndFeaturesEntries:
  - DisplayName: gohide
    Publisher: Xianwei Zhu
    DisplayVersion: 5.8.5
    ProductCode: gohide
    InstallerType: exe
ManifestType: installer
ManifestVersion: 1.6.0
